<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headScript(); ?>
        <?php echo $this->headLink(); ?>
        <title></title>
    </head>

    <body class="tundra">
        <table width="1048" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td><?php echo $this->layout()->content; ?></td>
            </tr>
        </table>
    </body>
</html>